name: Deploy to Staging

on:
  repository_dispatch:
    types: [ deploy-staging ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag to deploy (either `latest` or commit SHA)'
        required: true

jobs:
  deploy:
    environment: 
      name: Staging
      url: https://staging.digipedia.tudelft.nl
    runs-on: staging
    steps:
      - name: Resolve image to deploy
        id: resolve
        run: |
          if [ -n "${{ github.event.client_payload.tag }}" ]; then
            TAG="${{ github.event.client_payload.tag }}"
          elif [ -n "${{ github.event.inputs.tag }}" ]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            echo "No hash specified; failing."
            exit 1
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Deployed tag will be $TAG"

      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Pull image from Harbor
        run: docker pull ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/${{ github.event.repository.name }}:$TAG

      - name: Start container
        env:
          IMAGE_TAG: $TAG
        run: 
          docker compose -f ${{ secrets.REPO_ASSETS_PATH }}/docker-compose.yml --env-file ${{ secrets.REPO_ASSETS_PATH }}/.env up ${{ vars.CONTAINER_NAME }} -d --remove-orphans